# Generated by Django 5.0 on 2024-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0008_alter_data_chant_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='provenance_name',
            field=models.CharField(max_length=500, null=True, verbose_name='provenance'),
        ),
    ]
