# Generated by Django 5.0 on 2024-03-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0011_data_chant_incipit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='num_century',
            field=models.CharField(max_length=7, null=True, verbose_name='num_century'),
        ),
    ]
