# Generated by Django 5.0 on 2024-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0014_datasets_data_chant_dataset_sources_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_chant',
            name='feast_id',
        ),
        migrations.AddField(
            model_name='data_chant',
            name='feast_code',
            field=models.CharField(max_length=20, null=True, verbose_name='feast_code'),
        ),
    ]
