# Generated by Django 5.0.8 on 2024-11-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0016_datasets_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_chant',
            name='feast_code',
        ),
        migrations.RemoveField(
            model_name='feasts',
            name='feast_code',
        ),
        migrations.AddField(
            model_name='data_chant',
            name='feast_id',
            field=models.CharField(max_length=20, null=True, verbose_name='feast_id'),
        ),
    ]
