# Generated by Django 5.0.8 on 2024-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0017_remove_data_chant_feast_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_chant',
            name='feast_id',
        ),
        migrations.AddField(
            model_name='data_chant',
            name='feast_code',
            field=models.CharField(max_length=20, null=True, verbose_name='feast_code'),
        ),
    ]
