# Generated by Django 5.0.8 on 2024-11-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0018_remove_data_chant_feast_id_data_chant_feast_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasts',
            name='feast_id',
        ),
        migrations.AddField(
            model_name='feasts',
            name='feast_code',
            field=models.CharField(default='unknown', max_length=20, serialize=False, verbose_name='feast_code'),
        ),
    ]
