# Generated by Django 5.0 on 2023-12-31 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0003_remove_data_chant_siglum_sources_siglum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feasts',
            old_name='id',
            new_name='feast_id',
        ),
    ]
