# Generated by Django 5.0 on 2024-02-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0009_sources_provenance_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sources',
            old_name='provenance_name',
            new_name='provenance',
        ),
    ]
