# Generated by Django 5.0 on 2024-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0012_alter_sources_num_century'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='cursus',
            field=models.CharField(max_length=10, null=True, verbose_name='cursus'),
        ),
    ]
