# Generated by Django 5.0 on 2023-12-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantus_id', models.CharField(max_length=20, verbose_name='cantus_id')),
                ('siglum', models.CharField(max_length=20, null=True, verbose_name='siglum')),
                ('feast_id', models.CharField(max_length=20, verbose_name='feast_id')),
                ('source_id', models.CharField(max_length=500, null=True, verbose_name='source_id')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance_id', models.CharField(max_length=20, null=True, verbose_name='provenance_id')),
                ('provenance', models.CharField(max_length=500, null=True, verbose_name='provenance')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provenance_id', models.CharField(max_length=20, null=True, verbose_name='provenance_id')),
                ('century', models.CharField(max_length=50, null=True, verbose_name='century')),
                ('drupal_path', models.CharField(max_length=500, null=True, verbose_name='drupal_path')),
            ],
        ),
    ]
