# Generated by Django 5.0 on 2023-12-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feasts',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='feast_id')),
                ('feast_code', models.CharField(max_length=20, verbose_name='feast_code')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
            ],
        ),
        migrations.RenameModel(
            old_name='Source',
            new_name='Sources',
        ),
    ]
