# Generated by Django 5.0 on 2023-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0002_feasts_rename_source_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_chant',
            name='siglum',
        ),
        migrations.AddField(
            model_name='sources',
            name='siglum',
            field=models.CharField(max_length=20, null=True, verbose_name='siglum'),
        ),
    ]
