# Generated by Django 5.0 on 2024-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_repertoire', '0006_sources_num_century'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_chant',
            name='office_id',
            field=models.CharField(max_length=20, null=True, verbose_name='ofice_id'),
        ),
    ]
